name: Lint

on:
  pull_request:
  workflow_dispatch:

concurrency: 
  group: ${{ github.head_ref }}.lint
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ lint-machine-new ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run lintrunner on all files 
        run: |
          docker run --rm -v /proj/xbuilds:/proj/xbuilds -v /tools:/tools \
          -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }} -u z1aiebuild --network=host -e USER=z1aiebuild -e UID=95777 -e GRP=hd \
          -v /home/z1aiebuild/.ssh:/home/z1aiebuild/.ssh  -e GID=10115 --security-opt seccomp=unconfined \
          xcoartifactory.xilinx.com/vitis-ai-docker-dev-local/voe-dev-build:003 /bin/bash -c \
          " python -m pip install lintrunner lintrunner-adapters>=0.8.0 --force-reinstall 
          python -m pip install -r requirements-lintrunner.txt --force-reinstall
          export PATH=/home/z1aiebuild/.local/bin:$PATH
          lintrunner init
          lintrunner -v --force-color --all-files 
          "
